// Generated by CoffeeScript 1.4.0

describe("dataSpec", function() {
  var dataStore;
  dataStore = null;
  beforeEach(function() {
    return dataStore = socr.dataStore;
  });
  it("should create a dataObject", function() {
    dataStore.createObject("name", "socr");
    expect(dataStore.name).toBeDefined();
    return expect(typeof dataStore.name).toEqual("object");
  });
  it("should append data to existing data entry", function() {
    dataStore.createObject("test", {
      0: [1, 2],
      1: [3, 4]
    });
    expect(dataStore.test).toBeDefined();
    dataStore.createObject("test", {
      2: [1, 2],
      3: [4, 5]
    });
    expect(dataStore.test).toBeDefined();
    expect(dataStore.test.getData(0)).toEqual([1, 2]);
    expect(dataStore.test.getData(1)).toEqual([3, 4]);
    expect(dataStore.test.getData(2)).toEqual([1, 2]);
    return expect(dataStore.test.getData(3)).toEqual([4, 5]);
  });
  return it("should overwrite data to existing index", function() {
    dataStore.createObject("test", {
      0: [1, 2],
      1: [3, 4]
    });
    expect(dataStore.test).toBeDefined();
    dataStore.createObject("test", {
      1: [0, 0]
    });
    expect(dataStore.test).toBeDefined();
    expect(dataStore.test.getData(0)).toEqual([1, 2]);
    return expect(dataStore.test.getData(1)).toEqual([0, 0]);
  });
});
