// Generated by CoffeeScript 1.4.0

describe("appModel", function() {
  var model;
  socr.model = new socr.model();
  model = socr.model;
  beforeEach(function() {});
  it("should have a generateTrail function", function() {
    return expect(model.generateTrail).toBeDefined();
  });
  it("should be able to set a data set", function() {
    var input;
    input = {
      values: [[0, 1], [2, 3]],
      keys: [["H", "T"], ["T", "H"]],
      processed: true
    };
    return expect(model.setDataset(input)).toEqual(true);
  });
  describe("generating random samples", function() {
    beforeEach(function() {
      var input;
      input = {
        processed: true,
        keys: [["T", "T", "H", "T", "T", "H", "H", "T", "T", "H"], ["H", "H", "H", "T", "H", "T", "H", "T", "T", "T"]],
        values: [[0, 0, 1, 0, 0, 1, 1, 0, 0, 1], [1, 1, 1, 0, 1, 0, 1, 0, 0, 0]]
      };
      return model.setDataset(input);
    });
    return it("should generate a trail", function() {
      return expect(typeof model.generateTrail(1)).toEqual("object");
    });
  });
  return describe("testing calculations", function() {
    beforeEach(function() {
      return socr.dataStore.removeObject("all");
    });
    return it("should generate accurate P-value", function() {
      socr.dataStore.createObject("dataset.1.values", [1, 2, 3, 4, 5]);
      socr.dataStore.createObject("dataset.2.values", [4, 5, 6, 7]);
      window["test"] = model;
      return expect(model.getPof("dataset")).toEqual(0.03745653509411884);
    });
  });
});
